name: pull request
on:
  pull_request:
  # We require PRs to be up to date before merging so technically it is not needed run the rust job
  # on main. However for the cache to be usable in PRs we do need the job on main.
  push:
    branches: [git-action-test]
jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - run: |
          rustup --version
          rustup show
          cargo --version
          cargo +nightly fmt --version
          cargo clippy --version
      - run: cargo +nightly fmt --all -- --check
      - run: cargo clippy --locked --workspace --all-features --all-targets -- -D warnings
  
  nitpicker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ethanis/nitpicker@v1
        with:
          nitpicks: ".github/nitpicks.yml"
          token: "${{ secrets.GITHUB_TOKEN }}"

  doc-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --doc

  unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      # Shrink artifact size by not including debug info. Makes build faster and shrinks cache.
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - run: cargo build --tests
      - run: cargo nextest run
